"""initial schema

Revision ID: 70abf5109806
Revises: 
Create Date: 2026-07-15 11:14:44.834819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70abf5109806'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('registration_opens', sa.DateTime(), nullable=True),
    sa.Column('registration_closes', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'registration_open', 'registration_closed', 'in_progress', 'completed', name='tournamentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('organizer', 'athlete', 'coach', 'event_staff', 'fan', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_index(op.f('ix_user_roles_role'), 'user_roles', ['role'], unique=False)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('guardian_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tournament_staff',
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('event_staff', 'head_official', name='staffrole'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'user_id')
    )
    op.create_table('weight_classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_weight', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('min_weight', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_type', sa.Enum('lbs', 'kg', name='weighttype'), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brackets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('weight_class_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.Enum('single_elimination', 'double_elimination', 'round_robin', name='bracketformat'), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fan_follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('athlete_profile_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tournament_id', 'athlete_profile_id', name='uq_fan_follow')
    )
    op.create_table('registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('athlete_profile_id', sa.String(length=36), nullable=False),
    sa.Column('weight_class_id', sa.String(length=36), nullable=False),
    sa.Column('registered_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'withdrawn', 'disqualified', name='registrationstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('waiver_signed', sa.Boolean(), nullable=False),
    sa.Column('waiver_signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'athlete_profile_id', name='uq_registration_athlete_tournament')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bracket_id', sa.String(length=36), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('athlete_a_id', sa.String(length=36), nullable=True),
    sa.Column('athlete_b_id', sa.String(length=36), nullable=True),
    sa.Column('mat_number', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'bye', name='matchstatus'), nullable=False),
    sa.Column('winner_id', sa.String(length=36), nullable=True),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('win_condition', sa.Enum('decision', 'major_decision', 'tech_fall', 'pin', 'forfeit', 'disqualification', name='wincondition'), nullable=True),
    sa.Column('result_entered_by', sa.String(length=36), nullable=True),
    sa.Column('result_entered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_a_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['athlete_b_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['bracket_id'], ['brackets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bracket_id', 'round_number', 'match_number', name='uq_match_bracket_round_number')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('registration_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='paymenttxstatus'), nullable=False),
    sa.Column('stripe_intent_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=True),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('match_called', 'match_result', 'bracket_published', 'schedule_change', 'announcement', 'registration_reminder', name='notificationtype'), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('payments')
    op.drop_table('matches')
    op.drop_table('registrations')
    op.drop_table('fan_follows')
    op.drop_table('brackets')
    op.drop_table('weight_classes')
    op.drop_table('tournament_staff')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_user_roles_role'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('users')
    # ### end Alembic commands ###
